table Sales
	lineageTag: 74e752f0-9b99-4438-849f-e39926a85230

	column Product
		dataType: string
		lineageTag: 4bb4e0ef-de4a-4a07-a1e2-d73c67a3f2b9
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: 0
		lineageTag: f9ccfd35-f2a2-486a-98ff-b9ebbecf7380
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WclTSUTI0UorViVZKAjKNTcDMZCDT1AzMTAEyjQzAzFQg0xwimgZiglnpQBZQLBYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Product = _t, Sales = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Product", type text}, {"Sales", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

